### PR TITLE
Revert "Fix slice indices failure."

### PR DESCRIPTION
**Pull request by dunkmann00**
Now that indices are once again enabled in CP ([#4857](https://github.com/adafruit/circuitpython/pull/4857)), revert the changes from #31.

Tested with an itsybitsy M0.

### CODE REVIEW

**Comment by dunkmann00** [comment]
@kattni Have you had a chance to look at this?

**Comment by kattni** [comment]
@dunkmann00 Unless I'm missing something, the CircuitPython change is not present in the current stable version of CircuitPython, 6.3.0. This means anyone using the stable version would still run into this bug. Until 7.0.0 is stable, we should not revert this change.

**Comment by dunkmann00** [comment]
@kattni In CP 6.x branches the change wasn't needed because the flag that turned off slice indices functionality didn't yet exist. This flag was introduced when the newer versions of micropython were merged into CP in the main branch. But since 6.3.0 didn't have this, indices should work just fine.

**Comment by kattni** [comment]
@dunkmann00 Appreciate the follow-up. I'll test this out in the next day or two and get it merged if successful. Thanks for the fix!

**Comment by dunkmann00** [comment]
@kattni Np! I'll try to test it out myself as well.

**Comment by dunkmann00** [comment]
I can confirm this works on CP 6.3.0. Tested on an itsybitsy M0.

**Comment by dunkmann00** [comment]
Hey @kattni, just curious if you've had a chance to test this out on 6.3 yet?

**Comment by kattni** [comment]
@dunkmann00 I have not. Apologies for the delay. I should have time this week.

**Review by kattni — APPROVED** [review]
Tested on QT Py M0 on both 6.3.0 and 7.0.0-alpha.3.

Thanks for the fix!

**Review by kattni — CHANGES_REQUESTED** [review]
Actually, I just tested it with a basic slice, upon remembering that was the original issue, and it fails with the same error.

@dunkmann00 Thoughts?

On 7.0.0-alpha.3:
```
import board
import neopixel

pixel = neopixel.NeoPixel(board.NEOPIXEL, 1)

while True:
    pixel[0:1] = (255, 0, 0) * 1
```
Fails with:
```AttributeError: 'slice' object has no attribute 'indices'```

**Comment by kattni** [comment]
The slice code above works on 6.3.0 with this PR, but it turns the LED blue.

**Comment by dunkmann00** [comment]
> Actually, I just tested it with a basic slice, upon remembering that was the original issue, and it fails with the same error.
> @dunkmann00 Thoughts?

Thats actually kind of funny. It appears the change missed making it into 7.0.0-alpha-3 by about 10 hours 😆. So if you build from the tip of the main branch, it will be in there.

> The slice code above works on 6.3.0 with this PR, but it turns the LED blue.

Not sure about that, I'll look into it. I wonder, do you see that same effect without this PR as well?

**Comment by kattni** [comment]
I just pulled an adafruit_pypixelbuf.mpy out of a previous 6.x bundle folder, and yes the LED is still blue.

**Comment by dunkmann00** [comment]
Interesting, I don't have any neopixels with me at the moment so I'll look into it more later. One more question, does it only happen when you set them using a slice, or also when setting just one?

i.e.
`pixel[0:1] = (255, 0, 0) * 1`  - Result: Blue LED
AND
`pixel[0] = (255, 0, 0)`  - Result: ?

As another thought, I wonder if this is a board specific problem?

**Comment by kattni** [comment]
Setting a single pixel with `[0]` results in red.

**Comment by dunkmann00** [comment]
@kattni  I think you just need:
`pixel[0:1] = ((255, 0, 0)) * 1`
Because then it is a tuple of tuples, rather than a tuple of integers.

**Comment by kattni** [comment]
@dunkmann00 Actually it's supposed to be `[(255, 0, 0)]`, if I bothered to look up what I was doing and not try to do LED slices on the fly (I never get it right on the first try). 

The blue LED was my fault. So that's not an issue. 

However, I still need to test it on `main`. I would like to hold off on merging this until we do another 7 alpha release if that's necessary, because otherwise it won't work properly with both releases available on circuitpython.org.

**Comment by dunkmann00** [comment]
Sounds good to me!

**Review by kattni — APPROVED** [review]
Tested with 7.0.0-alpha.4 successfully!
